export const books = [
    {
        "name": "A Game of Thrones",
        "isbn": "978-0553103540",
        "authors": [
            "George R. R. Martin"
        ],
        "numberOfPages": 694,
        "publisher": "Bantam Books",
        "country": "United States",
        "mediaType": "Hardcover",
        "released": "1996-08-01T00:00:00", 
        "characters": [
             "https://anapioficeandfire.com/api/characters/2",
            "https://anapioficeandfire.com/api/characters/12",
            "https://anapioficeandfire.com/api/characters/13",
            "https://anapioficeandfire.com/api/characters/16",
            "https://anapioficeandfire.com/api/characters/20",
            "https://anapioficeandfire.com/api/characters/27",
            "https://anapioficeandfire.com/api/characters/31",
            "https://anapioficeandfire.com/api/characters/38",
            "https://anapioficeandfire.com/api/characters/39",
            "https://anapioficeandfire.com/api/characters/40",
            "https://anapioficeandfire.com/api/characters/41",
            "https://anapioficeandfire.com/api/characters/42",
            "https://anapioficeandfire.com/api/characters/46",
            "https://anapioficeandfire.com/api/characters/54",
            "https://anapioficeandfire.com/api/characters/56",
            "https://anapioficeandfire.com/api/characters/57",
            "https://anapioficeandfire.com/api/characters/60",
            "https://anapioficeandfire.com/api/characters/61",
            "https://anapioficeandfire.com/api/characters/62",
            "https://anapioficeandfire.com/api/characters/66",
            "https://anapioficeandfire.com/api/characters/67",
            "https://anapioficeandfire.com/api/characters/69",
            "https://anapioficeandfire.com/api/characters/79",
            "https://anapioficeandfire.com/api/characters/89",
            "https://anapioficeandfire.com/api/characters/107",
            "https://anapioficeandfire.com/api/characters/115",
            "https://anapioficeandfire.com/api/characters/116",
            "https://anapioficeandfire.com/api/characters/120",
        ]  
    },
    {
        "name": "A Game of Thrones",
        "isbn": "978-0553103540",
        "authors": [
            "George R. R. Martin"
        ],
        "numberOfPages": 694,
        "publisher": "Bantam Books",
        "country": "United States",
        "mediaType": "Hardcover",
        "released": "1996-08-01T00:00:00", 
        "characters": [
             "https://anapioficeandfire.com/api/characters/2",
            "https://anapioficeandfire.com/api/characters/12",
            "https://anapioficeandfire.com/api/characters/13",
            "https://anapioficeandfire.com/api/characters/16",
            "https://anapioficeandfire.com/api/characters/20",
            "https://anapioficeandfire.com/api/characters/27",
            "https://anapioficeandfire.com/api/characters/31",
            "https://anapioficeandfire.com/api/characters/38",
            "https://anapioficeandfire.com/api/characters/39",
            "https://anapioficeandfire.com/api/characters/40",
            "https://anapioficeandfire.com/api/characters/41",
            "https://anapioficeandfire.com/api/characters/42",
            "https://anapioficeandfire.com/api/characters/46",
            "https://anapioficeandfire.com/api/characters/54",
            "https://anapioficeandfire.com/api/characters/56",
            "https://anapioficeandfire.com/api/characters/57",
            "https://anapioficeandfire.com/api/characters/60",
            "https://anapioficeandfire.com/api/characters/61",
            "https://anapioficeandfire.com/api/characters/62",
            "https://anapioficeandfire.com/api/characters/66",
            "https://anapioficeandfire.com/api/characters/67",
            "https://anapioficeandfire.com/api/characters/69",
            "https://anapioficeandfire.com/api/characters/79",
            "https://anapioficeandfire.com/api/characters/89",
            "https://anapioficeandfire.com/api/characters/107",
            "https://anapioficeandfire.com/api/characters/115",
            "https://anapioficeandfire.com/api/characters/116",
            "https://anapioficeandfire.com/api/characters/120",
        ]  
    },
    {
        "name": "A Game of Thrones",
        "isbn": "978-0553103540",
        "authors": [
            "George R. R. Martin"
        ],
        "numberOfPages": 694,
        "publisher": "Bantam Books",
        "country": "United States",
        "mediaType": "Hardcover",
        "released": "1996-08-01T00:00:00", 
        "characters": [
             "https://anapioficeandfire.com/api/characters/2",
            "https://anapioficeandfire.com/api/characters/12",
            "https://anapioficeandfire.com/api/characters/13",
            "https://anapioficeandfire.com/api/characters/16",
            "https://anapioficeandfire.com/api/characters/20",
            "https://anapioficeandfire.com/api/characters/27",
            "https://anapioficeandfire.com/api/characters/31",
            "https://anapioficeandfire.com/api/characters/38",
            "https://anapioficeandfire.com/api/characters/39",
            "https://anapioficeandfire.com/api/characters/40",
            "https://anapioficeandfire.com/api/characters/41",
            "https://anapioficeandfire.com/api/characters/42",
            "https://anapioficeandfire.com/api/characters/46",
            "https://anapioficeandfire.com/api/characters/54",
            "https://anapioficeandfire.com/api/characters/56",
            "https://anapioficeandfire.com/api/characters/57",
            "https://anapioficeandfire.com/api/characters/60",
            "https://anapioficeandfire.com/api/characters/61",
            "https://anapioficeandfire.com/api/characters/62",
            "https://anapioficeandfire.com/api/characters/66",
            "https://anapioficeandfire.com/api/characters/67",
            "https://anapioficeandfire.com/api/characters/69",
            "https://anapioficeandfire.com/api/characters/79",
            "https://anapioficeandfire.com/api/characters/89",
            "https://anapioficeandfire.com/api/characters/107",
            "https://anapioficeandfire.com/api/characters/115",
            "https://anapioficeandfire.com/api/characters/116",
            "https://anapioficeandfire.com/api/characters/120",
        ]  
    },
    {
        "name": "A Game of Thrones",
        "isbn": "978-0553103540",
        "authors": [
            "George R. R. Martin"
        ],
        "numberOfPages": 694,
        "publisher": "Bantam Books",
        "country": "United States",
        "mediaType": "Hardcover",
        "released": "1996-08-01T00:00:00", 
        "characters": [
             "https://anapioficeandfire.com/api/characters/2",
            "https://anapioficeandfire.com/api/characters/12",
            "https://anapioficeandfire.com/api/characters/13",
            "https://anapioficeandfire.com/api/characters/16",
            "https://anapioficeandfire.com/api/characters/20",
            "https://anapioficeandfire.com/api/characters/27",
            "https://anapioficeandfire.com/api/characters/31",
            "https://anapioficeandfire.com/api/characters/38",
            "https://anapioficeandfire.com/api/characters/39",
            "https://anapioficeandfire.com/api/characters/40",
            "https://anapioficeandfire.com/api/characters/41",
            "https://anapioficeandfire.com/api/characters/42",
            "https://anapioficeandfire.com/api/characters/46",
            "https://anapioficeandfire.com/api/characters/54",
            "https://anapioficeandfire.com/api/characters/56",
            "https://anapioficeandfire.com/api/characters/57",
            "https://anapioficeandfire.com/api/characters/60",
            "https://anapioficeandfire.com/api/characters/61",
            "https://anapioficeandfire.com/api/characters/62",
            "https://anapioficeandfire.com/api/characters/66",
            "https://anapioficeandfire.com/api/characters/67",
            "https://anapioficeandfire.com/api/characters/69",
            "https://anapioficeandfire.com/api/characters/79",
            "https://anapioficeandfire.com/api/characters/89",
            "https://anapioficeandfire.com/api/characters/107",
            "https://anapioficeandfire.com/api/characters/115",
            "https://anapioficeandfire.com/api/characters/116",
            "https://anapioficeandfire.com/api/characters/120",
        ]  
    },
    {
        "name": "A Game of Thrones",
        "isbn": "978-0553103540",
        "authors": [
            "George R. R. Martin"
        ],
        "numberOfPages": 694,
        "publisher": "Bantam Books",
        "country": "United States",
        "mediaType": "Hardcover",
        "released": "1996-08-01T00:00:00", 
        "characters": [
             "https://anapioficeandfire.com/api/characters/2",
            "https://anapioficeandfire.com/api/characters/12",
            "https://anapioficeandfire.com/api/characters/13",
            "https://anapioficeandfire.com/api/characters/16",
            "https://anapioficeandfire.com/api/characters/20",
            "https://anapioficeandfire.com/api/characters/27",
            "https://anapioficeandfire.com/api/characters/31",
            "https://anapioficeandfire.com/api/characters/38",
            "https://anapioficeandfire.com/api/characters/39",
            "https://anapioficeandfire.com/api/characters/40",
            "https://anapioficeandfire.com/api/characters/41",
            "https://anapioficeandfire.com/api/characters/42",
            "https://anapioficeandfire.com/api/characters/46",
            "https://anapioficeandfire.com/api/characters/54",
            "https://anapioficeandfire.com/api/characters/56",
            "https://anapioficeandfire.com/api/characters/57",
            "https://anapioficeandfire.com/api/characters/60",
            "https://anapioficeandfire.com/api/characters/61",
            "https://anapioficeandfire.com/api/characters/62",
            "https://anapioficeandfire.com/api/characters/66",
            "https://anapioficeandfire.com/api/characters/67",
            "https://anapioficeandfire.com/api/characters/69",
            "https://anapioficeandfire.com/api/characters/79",
            "https://anapioficeandfire.com/api/characters/89",
            "https://anapioficeandfire.com/api/characters/107",
            "https://anapioficeandfire.com/api/characters/115",
            "https://anapioficeandfire.com/api/characters/116",
            "https://anapioficeandfire.com/api/characters/120",
        ]  
    },
    {
        "name": "A Game of Thrones",
        "isbn": "978-0553103540",
        "authors": [
            "George R. R. Martin"
        ],
        "numberOfPages": 694,
        "publisher": "Bantam Books",
        "country": "United States",
        "mediaType": "Hardcover",
        "released": "1996-08-01T00:00:00", 
        "characters": [
             "https://anapioficeandfire.com/api/characters/2",
            "https://anapioficeandfire.com/api/characters/12",
            "https://anapioficeandfire.com/api/characters/13",
            "https://anapioficeandfire.com/api/characters/16",
            "https://anapioficeandfire.com/api/characters/20",
            "https://anapioficeandfire.com/api/characters/27",
            "https://anapioficeandfire.com/api/characters/31",
            "https://anapioficeandfire.com/api/characters/38",
            "https://anapioficeandfire.com/api/characters/39",
            "https://anapioficeandfire.com/api/characters/40",
            "https://anapioficeandfire.com/api/characters/41",
            "https://anapioficeandfire.com/api/characters/42",
            "https://anapioficeandfire.com/api/characters/46",
            "https://anapioficeandfire.com/api/characters/54",
            "https://anapioficeandfire.com/api/characters/56",
            "https://anapioficeandfire.com/api/characters/57",
            "https://anapioficeandfire.com/api/characters/60",
            "https://anapioficeandfire.com/api/characters/61",
            "https://anapioficeandfire.com/api/characters/62",
            "https://anapioficeandfire.com/api/characters/66",
            "https://anapioficeandfire.com/api/characters/67",
            "https://anapioficeandfire.com/api/characters/69",
            "https://anapioficeandfire.com/api/characters/79",
            "https://anapioficeandfire.com/api/characters/89",
            "https://anapioficeandfire.com/api/characters/107",
            "https://anapioficeandfire.com/api/characters/115",
            "https://anapioficeandfire.com/api/characters/116",
            "https://anapioficeandfire.com/api/characters/120",
        ]  
    }
]